### PR TITLE
Update LLVM build instructions

### PR DESCRIPTION
**Pull request by marnovandermaas**
First is a minor fix of directory name from `llvm` to `cheriot-llvm`.
Second is some fixes to the `cmake` command:
- `${LLVM_PATH}` needs to be followed by `llvm` to find the correct folder.
- Remove some extra spaces in the command argumetns.
- Remove `LLVM_ENABLE_LLD` to resolve the following error on GCC
platforms:
```
CMake Error at cmake/modules/HandleLLVMOptions.cmake:298 (message):
  Host compiler does not support '-fuse-ld=lld'
```

### CODE REVIEW

**Comment by davidchisnall** [comment]
The first change looks good, but I don't like forcing a specific compiler (it should be fine to build LLVM with whatever your system compiler is).

**Comment by marnovandermaas** [comment]
> I don't like forcing a specific compiler (it should be fine to build LLVM with whatever your system compiler is).

Thanks, I've removed the forcing of the compiler.

**Comment by davidchisnall** [comment]
We might want to remove `LLVM_ENABLE_LLD` as well.  I'm not sure if this works on GCC platforms (I don't know if it checks whether LLD is supported by the compiler, or just unconditionally passes the flag).

**Comment by marnovandermaas** [comment]
> We might want to remove `LLVM_ENABLE_LLD` as well. I'm not sure if this works on GCC platforms (I don't know if it checks whether LLD is supported by the compiler, or just unconditionally passes the flag).

Good point, that was the source of the cmake error I reported earlier.

**Pull request merged**
