### PR TITLE
Adding features to the OpenTitanUart driver

### PR DESCRIPTION
**Pull request by HU90m**
I fleshed out the OpenTitan UART driver a little while working on https://github.com/lowRISC/sonata-software/pull/26. I don't think this is quite ready to be merged yet; opening this purely for visibility.

### CODE REVIEW

**Comment by davidchisnall** [comment]
There's a bunch of stuff in here that's just improving the existing code, rather than adding new things.  It would be great to have those merged soon (I don't anticipate problems with the other bits either).

**Comment by HU90m** [comment]
> There's a bunch of stuff in here that's just improving the existing code, rather than adding new things. It would be great to have those merged soon (I don't anticipate problems with the other bits either).

:+1: Rebased onto https://github.com/microsoft/cheriot-rtos/pull/278#event-13694639924 and marked as ready for review.

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
We probably need to document somewhere that this changes the behaviour of `stderr`, for anyone who is using `stdio.h`.

**Comment by HU90m** [comment]
> We probably need to document somewhere that this changes the behaviour of `stderr`, for anyone who is using `stdio.h`.

Where would be a good place to document this change?

**Comment by davidchisnall** [comment]
Good question.  A blog post maybe, and possibly in the Sonata bit of the [Getting Started](https://github.com/microsoft/cheriot-rtos/blob/main/docs/GettingStarted.md) doc?

**Pull request merged**
