### PR TITLE
Add std:string overload for Debug

### PR DESCRIPTION
**Pull request by PhilDay-CT**
Add an overload in debug for std:string based on the pattern for std::string_view

### CODE REVIEW

**Comment by davidchisnall** [comment]
Hmm, I’d hoped that you’d be able to just forward the string as a string view here, but that requires constructing an on-stack string view. I don’t really like adding another custom type directly.

It’s probably better to have a class that handles std::string as we do for enums and just calls the C string overload on the writer.

**Comment by rmn30** [comment]
Could we just resort to the underlying string like this?

```
template<>
struct DebugFormatArgumentAdaptor<std::string>
{
	__always_inline static DebugFormatArgument
	construct(const std::string &value)
	{
		return DebugFormatArgumentAdaptor<const char *>::construct(value.c_str());
	}
};
```

**Review by davidchisnall — APPROVED** [review]
Thanks, I forgot these were internally null terminated. Can you add a comment here reminding me to add a test for this when the compiler bug is fixed?

https://github.com/microsoft/cheriot-rtos/blob/58e3aee92a22604b9c75715fad45822e80229f46/tests/test-runner.cc#L96

**Comment by davidchisnall** [comment]
(Or add a test if there’s an easy way to do it that doesn’t trigger the compiler bug)

**Comment by PhilDay-CT** [comment]
>> (Or add a test if there’s an easy way to do it that doesn’t trigger the compiler bug)

I couldn't see a way to create a std::string to test with without hitting the compiler bug - could just hold of merging this PR until that's fixed, then we could add the test in there.   (There's no real rush from my side on this - I have a bunch of other stuff to get on with)

**Comment by rmn30** [comment]
It is possible to bypass the problematic constructor using C++14 string literals:
```C++
using namespace std::string_literals;
std::string s = "hello"s;
```
I think this is even very slightly more efficient as it doesn't result in a runtime call to `strlen`!

**Comment by davidchisnall** [comment]
#260 should make `__builtin_strlen` work, after the dev container has finished rebuilding.  Once that's merged, this can be rebased and merged (you can replace the test that uses `.c_str()` for printing, that was just to make sure that the `std::string` was correctly constructed).

**Comment by davidchisnall** [comment]
This is the dev container rebuild: https://cirrus-ci.com/task/5612295751991296

**Comment by davidchisnall** [comment]
The dev container fix is in and #260 is merged, so if you can rebase this (happy on the merge conflict to just throw away my test and add yours) then we can merge it.

**Comment by davidchisnall** [comment]
Did you rebase on main?

**Comment by davidchisnall** [comment]
I fixed the merge conflict, it just needs the indenting fixed.

**Comment by PhilDay-CT** [comment]
Sorry,  realised I'd pulled main from origin rather that upstream and sorted that out before I saw your last comment

**Pull request merged**
